In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# PROBLEM 1
Matrix product is calculated manually

**Question:**
$$A=\begin{bmatrix}-1&2&3\\
4&-5&6\\
7&8&-9\\
\end{bmatrix},B=\begin{bmatrix}0&2&1\\
0&2&-8\\
2&9&-1
\end{bmatrix}$$


**Answer:**
$$
\begin{bmatrix}(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*-8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*9)&(7*1)+(8*-8)+(-9*-1)
\end{bmatrix}
$$


**Final Answer**
$$
AB=\begin{bmatrix}
6&29&-20\\
12&52&38\\
-18&-51&-48
\end{bmatrix}
$$

# PROBLEM 2
Calculation by NumPy function

In [2]:
# np.matmul()
print("np.matmul()：\n{}".format(np.matmul(a_ndarray, b_ndarray)))

np.matmul()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
print()
# np.dot()
print("np.dot()：\n{}".format(np.dot(a_ndarray, b_ndarray)))


np.dot()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
print()
print("np.dot()：\n{}".format(a_ndarray @ b_ndarray))


np.dot()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# PROBLEM 3
Implementation of calculation of a certain element

In [5]:
answer_2 = (a_ndarray[0][0]*b_ndarray[0][0])+(a_ndarray[0][1]*b_ndarray[0][1])+(a_ndarray[0][2]*b_ndarray[0][2])
print(answer_2)

10


# PROBLEM 4
Creating a function that performs matrix multiplication

In [8]:
def cal_matrix (a,b):
    answer_2_1 = np.empty([3,3])
    for row_1 in range(a.shape[0]):
        for column_1 in range(b.shape[1]):
            answer_2_1[row_1][column_1] = sum(a[row_1,:]*b[:,column_1])
    return answer_2_1
print(cal_matrix(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### PROBLEM 4A
Matrix of combinations with undefined matrix product
$$D=\begin{bmatrix}-1&2&3\\
4&-5&6\\
\end{bmatrix},E=\begin{bmatrix}-9&8&76&-5&4\\
\end{bmatrix}$$

###
The matrix product DE is defined when the number of columns in D and the number of rows in E are equal, so it cannot be calculated in this example.
###

## PROBLEM 5
Judge the input whose calculation is not defined

In [10]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(cal_matrix(d_ndarray,e_ndarray))
else:
    print("This matrix cannot be calculated")

This matrix cannot be calculated


# PROBLEM 6
Transposition


In [11]:
def cal_matrix_2(a,b):
    if(a.shape[0]==b.shape[1]):
        results=np.matmul(a,b)
        return results
    else:
        return "This matrix cannot be calculated"
print(cal_matrix_2(d_ndarray,e_ndarray))
transposed_ndarray = np.transpose(e_ndarray)
print("after transpose {}, {}".format(d_ndarray.shape,transposed_ndarray.shape))
print("----------------------------------------------------")
print("solution {}".format(cal_matrix_2(d_ndarray,transposed_ndarray)))
    

This matrix cannot be calculated
after transpose (2, 3), (3, 2)
----------------------------------------------------
solution [[ 46  -4]
 [-34  73]]


In [15]:
## USING THE LIST COMPREHENSION METHOD 

In [14]:
#np.transpose() 
print(d_ndarray @ np.transpose(e_ndarray))

print()

# .T ()
print(d_ndarray @ e_ndarray.T)

[[ 46  -4]
 [-34  73]]

[[ 46  -4]
 [-34  73]]
