In [37]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

# PROBLEM 1
Enumeration of classes used so far


# Pandas
#### 1. pd.DataFrame

#### 2. pd.Series


# matplotlib
#### 1. plt.figure

#### 2. plt.subplots

# scikit-learn
#### 1. DecisionTreeClassifier

#### 2. LinearRegression

#### 3. RandomForestClassifier


# PROBLEM 2

Enumeration of methods and instance variables used so far

# METHODS

1. **numpy.reshape():** Gives a new shape to an array without changing its data.


2. **numpy.sum():** Sum of array elements over a given axis.



3. **list.append():**  Adds an iteam to the end of a list.


4. **pandas.loc():** Access a group of rows and columns by label(s) or a boolean array. .loc[] is primarily label based, but may also be used with a boolean array.


5. **pandas.iloc()** Purely integer-location based indexing for selection by position. .iloc[] is primarily integer position based (from 0 to length-1 of the axis), but may also be used with a boolean array.


# Instance Variable

1. **ndarray.shape:** Tuple of array dimensions.The shape property is usually used to get the current shape of an array, but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it.


2. **ndarray.size:** Number of elements in the array. Equal to np.prod(a.shape), i.e., the product of the array’s dimensions. 


3. **ndarray.data:** Python buffer object pointing to the start of the array’s data.


4. **array.ndim:** Number of array dimensions.


5. **array.dtype:** Data-type of the array’s elements.

# PROBLEM 3

Creating a standardized class by scratch

In [38]:
class ScratchStandardScaler():
    def fit(self, x):
        self.mean_ = np.mean(x, axis=0)
        self.var_ = np.var(x, axis=0)
        pass
    def transform(self, x):
        x_scaled = (x-self.mean_)/self.var_
        pass
        return x_scaled


In [39]:
data = load_iris()
x = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(x)
x_std = scratch_scaler.transform(x)
print(x_std)
print("Mean : {}".format(scratch_scaler.mean_))
print("Distributed : {}".format(scratch_scaler.var_))

[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]
Mean : [4.86 3.31 1.45 0.22]
Distributed : [0.0764 0.0849 0.0105 0.0056]


# PROBLEM 4

Creating a class that performs 4 arithmetic operations

In [44]:
class Calculator():
    def __init__(self, value):
        assert type(value) in [int, float], "only int or float"
        self.value = value
        print("Initial value {} has been set".format(self.value))
    def add(self, value2):
        self.value += value2
    def subtract(self, value3):
        self.value -= value3
    def multiply(self, value4):
        self.value *= value4
    def devide(self, value5):
        self.value /= value5

In [45]:
cal = Calculator(10)  
cal.add(5) ## Adding Number 5.
print("value : {}".format(cal.value))
cal.subtract(3)## Subtracting Number 3
print("value : {}".format(cal.value))
cal.multiply(2)## Multiply with Number 2
print("value : {}".format(cal.value))
cal.devide(6)## Divide by Number 6
print("value : {}".format(cal.value))

Initial value 10 has been set
value : 15
value : 12
value : 24
value : 4.0


In [46]:
cal2 = Calculator("10")

AssertionError: only int or float